name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi :wave:, <br /> We welcome all kinds of contributions, please feel free to contribute and/or ask questions. <br /> Someone will attend to your issue soon ☺️'
        pr-message: 'Hi :wave:, <br /> We welcome all kinds of contributions, please feel free to contribute and/or ask questions. <br /> Someone will attend to your PR soon ☺️'
